defaults:
  - _self_
  - /dataset: dsec

name: EventGenerator
# stream_embedding:
#   in_channels: 2
#   out_channels: 2
#   kernel_size: 3
#   stride: 2
#   padding: 1
#   step_mode: m
vocab_path: /root/code/event_vocab.pt
ckpt_path: null
# ckpt_path: /root/code/outputs/2024-08-30/15-40-32-861592-train-ratio-0.001-10ms-10bins/checkpoints/step_30_loss_1.1522.ckpt
mamba:
  d_model: 512
  d_intermediate: 0
  n_layer: 1
  vocab_size: 4096
  # ssm_cfg: dict = field(default_factory=dict)
  # attn_layer_idx: list = field(default_factory=list)
  # attn_cfg: dict = field(default_factory=dict)
  rms_norm: True
  residual_in_fp32: True
  fused_add_norm: True
  pad_vocab_size_multiple: 8
  tie_embeddings: True