# GPU precision: ['highest', 'high', 'medium'], for more details
# https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
gpu_precision: high
# See Docs for full flags and descriptions
# https://pytorch-lightning.readthedocs.io/en/stable/common/trainer.html#trainer-class-api
params:
  max_epochs: 200
  max_steps: 10000
  accelerator: gpu
  # single GPU: auto / multi GPUs: ddp
  strategy: auto
  # single GPU:0, / multi GPUs: 0,1,2,...
  devices: 0,
  # 32-true (32) for default, bf16-mixed/true for mixed precision
  precision: 32-true
  accumulate_grad_batches: 1  # Gradient accumulation every n batches
  gradient_clip_val: null
  log_every_n_steps: 10
  check_val_every_n_epoch: 1
  limit_train_batches: 1.0    # train on full dataset, can be used to toggle quick run
  limit_val_batches: 0.0      # 0.0 means no validation
  limit_test_batches: 1.0     # test on full dataset
  enable_model_summary: True  # Model summary before training process